
describe('外协运输',()=>{
  beforeEach(()=>   
  cy.visit("https://tpl-test.newchiwan.cn/"))

  
  it("登录-基本信息-开单-调度-外协运力-异常上报-发车-签收",()=>{
    cy.viewport(1920,1080)
    cy.get('#phone').type('18900000000')
    cy.get('#password').type('1111111l')
    cy.get('#code').type('1111')
    cy.get("[data-testid='signin-sumbit-button']").click()
    cy.title().should("include","TPL")

    // cy.contains("运力管理").click()
    // cy.contains("外协运力").click()
    // cy.contains("车辆管理").click()
    // cy.contains("添 加").click()
    // cy.get("[data-testid='car-province-select']").click()

    // cy.contains("京").click({force: true})
    // cy.get("[data-testid='car-plate-input']").type("20221017")
    // cy.get("#plateColorCode").click()
    // cy.contains("绿色").click({force: true})
    // cy.get("#vehicleTypeCode").click()
    // cy.contains("低栏").click({force: true})
    // cy.get("#vehicleLengthCode").click()
    // cy.contains("13").click({force: true})
    // cy.contains("确 定").click()

    // cy.contains("司机管理").click()
    // cy.contains("添 加").click()
    // cy.get("[data-testid='create-drivers-name']").type("司机姓名1")
    // cy.get("[data-testid='create-drivers-phone']").type("16111111111")
    // cy.contains("请选择或输入您的车牌号").click()
    // cy.contains("京20221017").click()
    // cy.contains("确 定").click()

    cy.contains("受理开单").click()
    cy.get(".ant-menu-title-content").should("contain","创建受理单")
    cy.contains("创建受理单").click()
    cy.get("#customerId").click()
    cy.contains('客户企业2').click()
    cy.get("#clientCode").type("20221013")
    cy.get("#shipperName").type("发货人1")
    cy.get("#shipperAddress").type("发货地址1")
    cy.get("#takeDeliveryAddress").type("收货地址1")
    cy.get("#orderCargoes_0_name").type("货物名称 11")
    cy.get("[data-testid='cargo-total-weight-input']").click({force:true}).type("200")
    cy.get("[data-testid='form-fee-input']").type("300")
    cy.get("[data-testid='create-order-submit-button']").click()
    cy.contains("运输管理").click()
    cy.contains("调度计划").click()
    cy.get(".ant-table-row.ant-table-row-level-0.custom-table-row button").contains('调度').click()   
    cy.get("[data-testid='dispatch-waybill-drivers-select']").click()
    cy.contains('010创建司机').click()
    cy.get("#planLoadingAt").click()
    cy.contains("此刻").click()
    cy.get("[data-testid='reach-oil-payment-input']").type(500)
    cy.get("[data-testid='confirm-button']").click()
    cy.contains("外协运输").click()
    cy.get(".ant-table-tbody >tr:nth-child(2) >td button").click()
    cy.contains("异常上报").click()
    cy.get("#anomalyTypeCode").click()
    cy.contains("货损").click()
    cy.get("#paymentType").click()
    cy.contains("到付款").click()
    cy.get("#revisedAmount").type(10)
    cy.contains("确 定").click()
    cy.contains("取 消").click()
    cy.title().should("include","TPL")
    cy.get(".ant-table-tbody >tr:nth-child(2) >td button > [data-testid='setting-icon']").click()  
    cy.contains("确认发车").click()
    cy.contains("确认到车").click()
    cy.contains("签收").click()
    cy.contains("财务管理").click()
    cy.contains("受理单结算").click()
    cy.contains("对账管理").click()

    cy.contains("知道了").click()
    
    cy.get(".ant-table-tbody >tr:nth-child(1) >td button").click()
    cy.contains("费用调整").click()
    cy.get("[data-testid='form-amount-input']").type(25)
    cy.contains("调 整").click()

  })
 


  })